query Dog {
  getDog(id: 555) {
    id
    name
  }
}

query Dogs {
  getDogs {
    id
    name
  }
}

mutation AddDog($dog: DogInput!) {
  addDog(dog: $dog) {
    id
    name
  }
}

mutation DeleteDog {
  deleteDog(id: 3)
}
